### ISSUE TITLE
Count number of new messages for a user?

### ISSUE THREAD

**Issue by extrakun** [cmgmyr/laravel-messenger#109]
I am trying to do a private mailbox function, and I would like to provide the number of new messages (not threads) for a  user. What is the most efficient way of doing it?

**Comment by a-komarev** [comment]
#80 would this help you?

**Comment by extrakun** [comment]
It looks like it would! I am rather new to GitHub, how do I pull a pull-request using composer?

**Comment by a-komarev** [comment]
@extrakun First of all you should define target fork in `repositories` block in `composer.json` file:

```json
"repositories": [
    {
        "type": "git",
        "url": "https://github.com/cybercog/laravel-messenger.git"
    }
]
```

After that you will be able to get branches from it. For example if you want to pull branch with name `hotfix/threads-relation` you should update `require` section in `composer.json` file by defining a branch name prefixed with `dev-` instead of writing package version for selected package:

```json
"require": {
    "cmgmyr/messenger": "dev-hotfix/threads-relation"
},
```
