### ISSUE TITLE
Play with multiple user tables/models

### ISSUE THREAD

**Issue by xuan9230** [cmgmyr/laravel-messenger#121]
Hi, in my website there are two different kinds of users(multi auth), let's say "student" and "consultant" instead of one kind of "user". 
According to the discussion in another issue, an easy approach is to modify the config file, but I guess if I hack like 

'user_model' => App\Student::class || App\Consultant::class,

obviously it won't work.. so how should I modify it?

PS: I use Auth::user("Student") or Auth::user("Consultant") in controllers and elsewhere, does it help?
PPS: @a-komarev mentioned that extending Thread.php, but since Student and Consultant both have a unique ID and they can talk to each other, is that necessary for me? 

Many thanks!

**Comment by sellegabuya** [comment]
I'm also facing the same issue.
Thanks for bringing this up :)

**Comment by a-komarev** [comment]
All these users are in one table? If so - you can easily display different views for different groups by getting user type (role, or group) as you named it.

**Comment by a-komarev** [comment]
If you have many types of users which not sharing the same ID you can overwrite package models and add polymorphic relation instead single user.

**Comment by cmgmyr** [comment]
The only way that I can see this happening is if you do what @a-komarev mentioned - overwriting package models and adding some additional relationships. 

Right now I don't think handling multiple "user" models should be in the package since it's not aligned to how Laravel treats users. I'm going to close this for now, but feel free to keep the conversation going if needed.
