### ISSUE TITLE
Thread.php function for received messages only

### ISSUE THREAD

**Issue by javaftper** [cmgmyr/laravel-messenger#126]
Hi,

Great package thanks.

I've implemented my create.blade.php and MessagesController.php:create() to restrict messaging to one-to-one as I don't want multiple recipients.

index() on MessagesController.php provides three options for listing threads.  They all list messages that have been participated in whereas I want to list all received messages with new messages indicator (inbox type functionality).

Could someone advise how I could adapt the following method from Thread.php to provide this functionality?
`
    public function scopeForUserWithNewMessages($query, $userId)
    {
        $participantTable = Models::table('participants');
        $threadsTable = Models::table('threads');

        return $query->join($participantTable, $this->getQualifiedKeyName(), '=', $participantTable . '.thread_id')
            ->where($participantTable . '.user_id', $userId)
            ->whereNull($participantTable . '.deleted_at')
            ->where(function ($query) use ($participantTable, $threadsTable) {
                $query->where($threadsTable . '.updated_at', '>', $this->getConnection()->raw($this->getConnection()->getTablePrefix() . $participantTable . '.last_read'))
                    ->orWhereNull($participantTable . '.last_read');
            })
            ->select($threadsTable . '.*');
    }
`

**Comment by cmgmyr** [comment]
Thanks for using the package! It sounds like you just need to use that exact method:

`$threads = Thread::forUserWithNewMessages($currentUserId)->latest('updated_at')->get();`

Will return all of the threads that have unread messages for the current user. In a one-to-one messaging app, a user has to be a participant in order to have access to the thread. Please update this ticket if you need any further assistance.
