### ISSUE TITLE
newThreadsCount()

### ISSUE THREAD

**Issue by elchejek** [cmgmyr/laravel-messenger#139]
Hello,

i would like to implement newThreadsCount into appserviceprovider, so variable would be shared to all views - navbar, dashboard, etc. Has anyone any suggestions how to do that?

I have tried with:

> public function boot()
>     {
> 
>         if (Auth::user()){
>         $countMsg = Auth::user()->newThreadsCount();
>         view()->share('countMsg',$countMsg);
>         }
> 
>     }

but it is not working. I get  Undefined variable: countMsg.

BR
Ed

**Comment by cmgmyr** [comment]
The problem is that your views are looking for this variable, which is only available if the current user is logged in. So something like this should work better:

```php
$countMsg = 0;

if (Auth::user()){
    $countMsg = Auth::user()->newThreadsCount();
}

view()->share('countMsg', $countMsg);
```

I'd suggest looking into [View Composers](https://laravel.com/docs/5.2/views#view-composers) instead of putting this in a service provider.
