### ISSUE TITLE
How to keep the messages between two users in a single thread?

### ISSUE THREAD

**Issue by Ramir1** [cmgmyr/laravel-messenger#15]
How to keep the messages between two users in a single thread?
Is it possible?

**Comment by cmgmyr** [comment]
Yes, you can definitely do that.

1. In your `MessagesController@index` method, you'll have to use `$threads = Thread::forUser($currentUserId);` as shown in the [example file](https://github.com/cmgmyr/laravel-messenger/blob/master/src/Cmgmyr/Messenger/examples/MessagesController.php#L38). This will make sure that your users only see the threads that they are participating in.
2. In your `MessagesController@show` method you'll have to do a check in order to see if the current user is a participant in the thread that they are requesting. You can do this fairly easily - after [line 55](https://github.com/cmgmyr/laravel-messenger/blob/master/src/Cmgmyr/Messenger/examples/MessagesController.php#L55) add: `$thread->getParticipantFromUser(Auth::id());`
3. You'll have to create a different route for your `create` method that will include a `user id` to add as a participant. So maybe something like `Route::get('create/{toUser}', ['as' => 'messages.create', 'uses' => 'MessagesController@create']);` Then in your `store` method you'll just use the `current user id` and the `toUser` as the participants.

I hope that helps, please let me know if you have any other questions.

**Comment by dincio** [comment]
@cmgmyr im lost in this part "Then in your store method you'll just use the current user id and the toUser as the participants." how to do that?

**Comment by cmgmyr** [comment]
This is one way you can do it

    public function store($toUser) {
	// get input

	// save thread

	// save message

	// sender (same as example)
	Participant::create(
	    [
	        'thread_id' => $thread->id,
	        'user_id'   => Auth::user()->id,
	        'last_read' => new Carbon
	    ]
	);

	// recipients (new)
	$thread->addParticipants([$toUser]);

	// redirect
    }

So you are saving the sender the same as the example, and only adding one other user as a recipient. In your UI you just don't give an option to add more participants to a thread. Make sense?
