### ISSUE TITLE
Chat messages sent at the same time

### ISSUE THREAD

**Issue by nikolaynesov** [cmgmyr/laravel-messenger#161]
Hi guys,

I am developing a **chat app** based on this package. The thing I am worried about is if 2 users in the same chatroom(thread) send **1 message at exactly the same time**, the same second. So bearing this in mind there are 3 questions:
1) Should I use a **milliseconds timestamp** for messages as an additional column?
2) Should I add a **unique index** on this _new column_ and _thread_id_?
3) @cmgmyr If all these makes sense to you, are you going to include it to the package in case I make a pull request to update the migration?

**Comment by a-komarev** [comment]
@nikolaynesov I have only one question why you so bothered about such precision? Can you provide use case for it?

Messages will be ordered in sequence they were written in database. So if user2 sent message on 1 millisecond earlier than user1 you will have user2 message with lower id. Isn't it enough?

**Comment by a-komarev** [comment]
Take a look at [Fractional seconds in MySQL](http://dev.mysql.com/doc/refman/5.7/en/fractional-seconds.html). But I'm not sure this implemented in all other databases.

If you will add separate column for milliseconds and they will be unique then you'll need to add 1 extra digit from 0 to 9 on the end which will allow you to have 10 concurrent messages in one millisecond, this should be enough.

First of all you will need to find is there any records in such second + milliseconds exists but ignores latest digit, if yes - take latest digit, increments it and add a new record.

But there is one issue with all this behavior - performance. If you afraid of a lot of concurrent requests and will have a unique index - your should take into account that hardware requirements will be increased significantly because Unique index slows down all write requests and chats are mostly doing write requests, not read.

**Comment by cmgmyr** [comment]
@nikolaynesov I personally think the milliseconds timestamp is a bit overkill for most applications, but if you did need to still move forward with implementing it @a-komarev's solution seems like a good one to me.

At this time I don't think adding a milliseconds timestamp would be a good addition to the package, as most applications wouldn't utilize it. I'll be sure to keep an eye out for additional requests in the future, and if there is enough call for this sort of thing, then it would make sense to implement it.

I'm going to close this issue for now, but feel free to keep the conversation going if you need anything else!

**Comment by nikolaynesov** [comment]
@a-komarev,
Thank you for attention and advise. 
May be I am missing something. I need to sort somehow the messages on frontend. It is not a problem though, but the only thing I am worried about is if 2 participants send a message at the same second how I would display them. Of course I can sort messages by ID or by created_at + ID. In this case I have to disclose message id to the user but it does not look like a vulnerability, right? In case I need to get an additional part of messages history dynamically I can use the last message id to get previous messages. Does it make sense? 

@cmgmyr sure, thank you.

**Comment by a-komarev** [comment]
@nikolaynesov yes, you can use ids to get older messages.

If you are worried about people know real IDs of the records - use `Hashids` or `Optimus`.

Then when you are trying to get older messages you need to bypass to server side masked identifier of the oldest message on your screen, decode it there and perform a query.

**Comment by nikolaynesov** [comment]
@a-komarev , 

It's fine to use user ID to get older messages. But with Hashids do you think it will make an extra load on the server? Why not to use guid (uuid) as primary key (base64 encoded or in binary type)? And the main question: what are potential risks of disclosing real ids in this situation? 

PS: using Hashids or GUID makes it impossible to order messages by ID&Date with js on frontend. So we can only order them by Date with precision to seconds.

**Comment by a-komarev** [comment]
@nikolaynesov If you want to rely to the messages unique identifier to get older messages you'd better to use auto incremented field because UUID isn't sequenced.

If you want to use UUID\GUID instead of auto incremented id\hashids you will have additional query to get record with provided UUID, and only after it you will be able to get older records. But anyway you would have an auto incremented field to keep records in database in correct sequence.

With Hashids you can easily get unique ID by decoding a hash. Take a look how Facebook and Twitter is doing requests for an older records, they are using something similar but with their own implementations.

You can store encoded hashids in extra column in messages table and perform encoding part only once on record creation. I recommend to write a benchmarks to test Hashids encoding\decoding stuff. I'm not sure it's too "heavy" operation. And one more thing... users are requesting old messages not frequently, so decoding wouldn't be a big problem.

Risks I could see if real ID is provided:

- User can see how many messages has been sent.
- Possibility to get\edit others private messages if you forgot to add validation.
