### ISSUE TITLE
Error with addParticipants() and link_to()

### ISSUE THREAD

**Issue by March3se** [cmgmyr/laravel-messenger#171]
I'm using the last Laravel version (5.3) and I have used the last package version.

I get two errors:

the first when I send the message:

```
BadMethodCallException in Builder.php line 2440:
Call to undefined method Illuminate\Database\Query\Builder::addParticipants()
```

The second when I go in the message page (index) and I get this error:
```
FatalErrorException in a2a91e8811658891cc7ce51649e5951e1e02bb01.php line 13:
Call to undefined function link_to()
```

**Comment by cmgmyr** [comment]
1. `addParticipants()` should be `addParticipant()` (without the plural `s`)
2. `link_to()` is in the example files because of the use of the [laravelcollective/html](https://laravelcollective.com/docs/5.3/html) package. I mentioned this in the package readme, but you might have missed it. If you bring in this package, then this function will be available. However, if you choose not to use the package, then you'll have to create links through Laravel's helpers, or on your own.

I hope this fixes your errors. If it doesn't, or have any other questions, please feel free to comment on this thread.
