### ISSUE TITLE
One thread for two participants

### ISSUE THREAD

**Issue by kevintr2** [cmgmyr/laravel-messenger#206]
Hey,

First of all thank you for this package, it's really amazing. I read the issue where you explain how to get only one thread for two participants, but the point that i don't understand is when you create a new Route (in my case /messenger/create/{$toUser}) -> how can we know, before selecting the participant who we want to send a message to, what his userid is? 

Thank you 

edit: ok if i understand it right, you know the user_id from the recipient because you can only send messages by clicking "send msg" in the recipients profil am i right?
if i am, i still don't understand at which part , of the modifications you've given, we say that we only want one thread per couple (auth user id & recipient user id)

**Comment by cmgmyr** [comment]
Thanks for using the package! I'm glad that it's helping you in your app.

Hopefully, I'm understanding this all correctly, so first when a logged in user goes to `/messenger/create/{$toUserId}`, you'll have the creator (you) as `Auth::id()` and the only other participant once you send the message getting set to `$toUserId`. In the examples, there are parts of the view to select additional participants for the thread, but you can get rid of all that logic since you only want the one given in the URL.

So once the thread and message is created, your `Auth::id()` user gets set as the creator, and `$toUserId` is added by `$thread->addParticipant($toUserId)`.

This can all be done via the user's profile page in your instance since you have the id of the user that you're on and the user id of the current user.

So now for your `/messenger/show/{id}` route you can do something like:
```php
$thread = Thread::find($id);
if(!$thread->hasParticipant(Auth::id())) {
    // handle redirects, error messages, etc
}

// continue on and return the view
```

The current and basic set up of the package is that users can keep adding threads to the system - even if it's the same 2 people in multiple threads. If you want it to be more of a true facebook style (where each message gets added onto a previous thread) you'd just have to do a quick check to see if the 2 participants already have a thread and if they do, just append the new message to it. If not, then create a new thread instance.

I hope that I covered everything that you were asking. I'm going to close this as an issue for now, but if you have any other questions, feel free to add it here

**Comment by kevintr2** [comment]
Thank you for your quick response

Ok i'll try that, you answered part of my question. In fact i want to do something like facebook, i only want one thread for 2 same persons. And i thought about, like you said, doing a check to see if a thread already exists between those 2 persons but i'm still confused about the if condition. Should i search in the threads table or participants?

**Comment by cmgmyr** [comment]
You would query the `participants`, but something like this would be a lot easier...

```php
try {
    $thread = Thread::between([Auth::id(), $toUserID])->latest('updated_at')->firstOrFail();
} catch (ModelNotFoundException $e) {
    $thread = Thread::create(['subject' => $input['subject']]);
}

// carry on with activating participants, add message, etc.
```

You might want to do some additional checks and/or cleanup if there are multiple threads found

**Comment by kevintr2** [comment]
Thank you mate ! :)

**Comment by lilian21** [comment]
Hello guys, I have a similar issue with the one described here, that's why I didn't open a new issue.
   I need to create a mix between messenger and chat, a real time messenger, just like facebook.         Conversations are always between two users. I already created the "real-time" part of it but now I have to create the mechanism to store messages. This package seems the best option but I still don't understand why I need to create a thread with a "subject". Ok, for the real purpose of this package it makes sense but for my case do I really need this or what would be the best option for the subject name?
Another question is what the activating participants means?

Thank you,
Lilian

**Comment by a-komarev** [comment]
@lilian21 You can make thread with empty subject: `'subject' => ''`, or update migration file where you will define that subject could be `nullable`.

**Comment by cmgmyr** [comment]
@lilian21 since soft deletes are enabled on `participants`, activating the thread will restore all `participants` to the thread. This is helpful if you have additional options to mute or leave a thread. You can see how it works [here](https://github.com/cmgmyr/laravel-messenger/blob/424516c509579dcf73875089e013425275635761/src/Cmgmyr/Messenger/Models/Thread.php#L285) but it's usage is optional

**Comment by lilian21** [comment]
Thank you guys for your helpful and swift responses. Cheers!
