### ISSUE TITLE
Optimized Samples?

### ISSUE THREAD

**Issue by HDVinnie** [cmgmyr/laravel-messenger#213]
Can we possible get some "more advanced" samples? The current ones provided now could use a update.

This isnt a "issue" so to say but would really help beginners like me.

http://imgur.com/a/HwjiS

**Comment by cmgmyr** [comment]
Thanks for the feedback! The examples are just a starting point to show what you could do, or at least what information is needed throughout the rest of the package. It's certainly not a fully "recommended" implementation. I agree that this may not be super clear and it would be helpful for some other examples.

The idea of creating this package is to have something flexible enough to use in multiple applications and with that not being super opinionated about implementation. For example, the checkboxes are just used to show the potential participants names and use the IDs of each. The checkbox example could be changed to a multiple selection dropdown, [typeahead](https://twitter.github.io/typeahead.js/examples/) or similar look up, or anything else. All the package needs is a list of user ids.

I was actually very hesitant to include any examples at all since I didn't want developers to implement exactly what they saw and create their own implementation. I also know that this is harder for some, so decided to include them anyways.

I'll work on some additional examples and/or documentation to make this more clear. Thanks again for the feedback!

**Comment by HDVinnie** [comment]
Thanks so much.....Im on a path to learn more and love Laravel. Im a frontend guy so have a lot to learn about doing backend. No rush but if anyone can provide some other examples to help those like me learn by seeing the different ways it would be much appreciate. Thanks for all the work to those that contribute to @cmgmyr package.

**Comment by ajuchacko91** [comment]
I came to ask to add more good documentation. And i saw this thread . Hope Good Doc will be on the way. Thanks
