### ISSUE TITLE
Additional custom column for Threads

### ISSUE THREAD

**Issue by nikolaynesov** [cmgmyr/laravel-messenger#214]
Hi,

Is there a way to safely add additional custom column to Threads table?
Can I do it like that (without forking the package):
1) Create migration to add the column in my app
2) Create a new eloquent Model, that will extend the `Cmgmyr\Messenger\Models\Thread` and add the column, put getters and setter for this column etc...

BTW: It's possible to create multiple active threads between same 2 users (participants), right?

**Comment by cmgmyr** [comment]
Hey @nikolaynesov,
Yes, that's exactly how you would do it, with an addition of step 3: add your new model to the [config file](https://github.com/cmgmyr/laravel-messenger/blob/master/src/config/config.php#L11). This will reference your new model instead of the package's model. Then you should be all set.

Yes, you can create as many threads as you wish with the same participants. If you'd like to change that you'd have to implement your own logic.

Let me know if you need anything else. Thanks for using the package!

**Comment by nikolaynesov** [comment]
Amazing, thank you for this cool package & fast response!
