### ISSUE TITLE
How to delete messages?

### ISSUE THREAD

**Issue by MrMooky** [cmgmyr/laravel-messenger#223]
Hello. I could not find a method for deleting a message and/or a whole thread. Is something like this planned in the near future or should I create my own function?

**Comment by cmgmyr** [comment]
Hey @MrMooky - currently there is no delete functionality built into the package, but all models have soft-deletes enabled. I thought it was best to leave deleting functionality up to the app developer since there are a lot of different directions to go. There will probably be a more opinionated option in `v3` but that is still in the early stages with no ETA. In the meantime, you're able to create your own functionality. If you have any other questions, please let me know.

**Comment by cmgmyr** [comment]
Hi @AmeerHamza33 it really depends on how you want to remove the messages and/or participants. There are a bunch of different [threads](https://github.com/cmgmyr/laravel-messenger/issues?q=delete) in the repo
