### ISSUE TITLE
admin messaging

### ISSUE THREAD

**Issue by kevokaykey** [cmgmyr/laravel-messenger#264]
How can I use this messaging system for  only users to talk to the admin .Admin  is using another model

**Comment by ysfkaya** [comment]
Is there any progress on this issue ?

**Comment by Gummibeer** [comment]
To allow multiple models as participant you have to make the `user_id` column in the `participants` table polymorph https://laravel.com/docs/5.6/eloquent-relationships#polymorphic-relations
After this you can send to all models you want. I think that this could be also a good library change to allow multiple user models. But this needs a lot of changes, will produce BC (new major version) and I have no usecase for this atm.

But in general I recommend to use authorization, roles, groups and abilities to handle admin and other things instead of two different models. This makes everything just a lot more complicated (authorization, middlewares, user resolving and so on).
