### ISSUE TITLE
Soft-delete just for one user

### ISSUE THREAD

**Issue by JuliaSivartsson** [cmgmyr/laravel-messenger#40]
When I delete a message as a user, it gets deleted for all the participants. Is there a way to change this so that it just gets deleted for the user who pressed 'delete' or do I have to change the whole table structure for this?

**Comment by cmgmyr** [comment]
Thanks for posting this. I'll look into it

**Comment by esseremmerik** [comment]
Great, would love to see this feature too. Perhaps we will add this and give you a pull request so you can see if it fits in your vision for the package as well!

**Comment by Kryptonit3** [comment]
This would require a bit of logic.

When user deletes message (Thread) from inbox, should they get a new message or reinstated into the Thread if a new reply is made? should they get the entire message back or just the new messages? Can users delete individual messages (Message) from a Thread?

A bit to think about.

**Comment by Kryptonit3** [comment]
Just add a deleted boolean to participants table default false. User deletes thread, update to true. If new reply reset to false.

**Comment by maximl337** [comment]
The way I solved this problem ( not a perfect solution ) is to make a pivot table `archived_messages` that contains `user_id`, `message_id`. then in Message model $this->belongsToMany('App\User', 'archived_messages'); and in User Model $this->belongsToMany('App\Message', 'archived_messages'), then on delete: App\Message::findOrFail($id)->archived_message()->attach($user_id); what do u guys think?

**Comment by lorvent** [comment]
will this issue addressed in V3?

**Comment by divdax** [comment]
+1

**Comment by mahony0** [comment]
Any progress on this?

**Comment by theunreal** [comment]
More than a year for a really important feature? |:

**Comment by a-komarev** [comment]
I'm working on it, but because the lack of time progress is pretty slow :'(

Anyway, you should keep in mind that implementing such feature will drastically increase server requirements :D

**Comment by Gummibeer** [comment]
Like I see here are many ways described so here is also a main logic problem like @Kryptonit3 said.

The request was "delete messages for a single user": so not archiving them, deleting the whole thread or removinjg him as a participant. These are all ways that are possible with the current setup but wasn't requested.

The only solution, I see, here would be something like @maximl337 described, but just with `deleted_messages`. Cause archiving is something similar to facebook or whatsapp where you can archive messages/threads and than they are just in another list and not removed.
In addition to the described solution I would use a scope and use it in the relation methods directly.

**Comment by a-komarev** [comment]
Just a couple thoughts on the logic.

## User delete message

I can see no problems here, we are just marking specific message as deleted for specific user.

## User delete thread

Threads could be of 2 types:

- **Group thread** where with any amount of participants
- **Private thread** with only 2 participants.

### Group thread

An issue here is to understand if user wants to delete the thread from his list or just to clean all the messages in it. But it solves with 2 different action buttons.

- **Clean thread history** should collect all not deleted messages and mark them as deleted.
- **Delete thread** perform `Clean thread history` and remove user from participants list.

*Cleaning messages on thread delete is required, otherwise user will see deleted messages after re-joinning thread. If we don't want to delete old messages we have common leave thread method.*

### Private thread

An issue here is to understand if user wants to clean all the messages in thread, delete thread from his list but continue to receive messages or completely delete thread & block sender.

- **Clean thread history** should collect all not deleted messages and mark them as deleted.
- **Delete thread** perform `Clean thread history` and mark thread as deleted for specific user but remove this mark on first received message in deleted thread.
- **Block thread** perform `Clean thread history`, perform `Delete thread` and mark it as blocked (what means that new messages in thread wouldn't remove deleted mark from it).

*Cleaning messages on thread delete is required, otherwise user will see old messages after receiving new ones.*

All this stuff is unoptimized yet. Just first summary boilerplate.

**Comment by Gummibeer** [comment]
@a-komarev the *block* functionality should also be possible in the group chat - if I don't want to be part of this thread no one should force me to be.

So in main we have a list of actions possible with messages and/or threads: *archive*, *delete*, *leave*, *block*

*archive*: flag the thread as archived, don't display it in the normal list and unflag it on new messages.
*delete*: flag the message/thread as deleted and hide it in all lists
*leave*: remove the participant and don't readd it on new messages - it needs a real reinvitation
*block:* archive it, leave it, flag thread as blocked and prevent a reinvitation

**Comment by theunreal** [comment]
I think you take it too far atm, Actually all is needed is removing a participant from a thread. Once he is not patricpantin in a thread, it will not be displayed in his list of threads (`$user->threads()`) and when the last participant leaves - the thread will be deleted permenantly.

The block, archive and leave actions can be added later as another issue..

**Comment by Gummibeer** [comment]
@theunreal but leaving a thread is possible!? This is nothing new.

**Comment by maximl337** [comment]
For the scope of this issue I think the best way would be to use a `deleted_messages` table with `user_id` and `message_id`. Then when getting messages / threads for users, omit the message ids that are in the deleted_messages table.

**Comment by a-komarev** [comment]
@maximl337 it will be enough for the small projects and will be good quick solution, but later optimizations will be needed.

**Comment by cmgmyr** [comment]
Thank you for giving this request a kick in the butt and for all of the additional information everyone has posted. All of the info is very helpful. I apologize for not updating this in a while - as you can see, there is much more to this than just deleting a participant of a thread, so I've had this on the backburner. I do like the idea of there being participant actions in a thread, but I want to make sure the overhead of managing these is at a minimum. I'm going to try out some different ideas and will keep everyone posted once I have something more concrete. In the meantime, if anyone else has anything to add, please feel free to chime in!

**Comment by cmgmyr** [comment]
Quick update on this issue. Since soft deletes are already implemented for participants, a new method was added in [2.12](https://github.com/cmgmyr/laravel-messenger/releases/tag/2.12) to remove a participant from a thread, which should fix this initial issue. By using Laravel's default soft delete methods, a developer could write their additional actions if needed. I'm going to close this ticket for now and open a new one in regards to possibly adding additional actions into the package.
