### ISSUE TITLE
thread hijacking

### ISSUE THREAD

**Issue by FrankDupree** [cmgmyr/laravel-messenger#43]
hi, first things first, your package is awesome!! don't know if i did something wrong, but i noticed that a user who wasn't invited to a thread can join once she adds the thread id manually. lets say the user is on http://localhost:8000/messages/7..the user also has access to http://localhost:8000/messages/8 thereby inviting themselves in and is able to send a message which automatically adds the user to the thread list of participants..did i do something wrong?

**Comment by cmgmyr** [comment]
Hey Frank, I'm glad you like the package! This package was actually designed that way. Since it can be used in multiple ways (open forum, group messages, and private messages) I didn't want to limit it in any way. The potential drawback of this is that the developer is responsible for choosing how to use it and implement the best practices around that option.

So in an open forum, all users would be able to see and get to all messages, but in your case it sounds like you want either group, or private messaging. In the method that you are showing the message, you'll have to make a call to check to see if the authenticated user is a participant on the thread. If not, they should be redirected somewhere else.

I hope that all makes sense. If you have any questions, please feel free to leave another comment on this thread. I'm going to close it for now.

**Comment by askaoru** [comment]
In case you are wondering how you could restrict a non-participant from inviting themself, here's an example of how i did it. Probably not the best way but it works for me.
This is in your controller.

    /**
     * Shows a message thread
     *
     * @param $id
     * @return mixed
     */
    public function show($id)
    {   
        try {
            $thread = Thread::findOrFail($id);
        } catch (ModelNotFoundException $e) {
            Session::flash('error_message', 'The thread with ID: ' . $id . ' was not found.');

            return redirect('messages');
        }
        
        $userId = Auth::user()->id;
        $participant = $thread->participants()->where('user_id', '=', $userId)->get();
        
        if($participant != '[]'){
            $thread->markAsRead($userId);

            return view('messenger.show', compact('thread'));
        }else{
            Session::flash('error_message', 'This conversation does not involves you');

            return redirect('messages');
        }
    }

**Comment by a-komarev** [comment]
@askaoru Thanks for sharing a solution for it!

**Comment by FrankDupree** [comment]
@cmgmyr tnx for the insights, well said..@askaoru just what i needed, you saved me the stress of cooking one up myself, you the man! tnx :+1:

**Comment by cmgmyr** [comment]
Would something like a `$thread->hasParticipant($userId)` be helpful for this sort of thing?

That way, it makes @askaoru's solution a little cleaner...

```php
public function show($id)
{   
    try {
        $thread = Thread::findOrFail($id);
    } catch (ModelNotFoundException $e) {
        Session::flash('error_message', 'The thread with ID: ' . $id . ' was not found.');

        return redirect('messages');
    }

    if($thread->hasParticipant(Auth::id())){
        $thread->markAsRead($userId);

        return view('messenger.show', compact('thread'));
    }else{
        Session::flash('error_message', 'This conversation does not involves you');

        return redirect('messages');
    }
}
```

**Comment by FrankDupree** [comment]
@cmgmyr yeah it does, nice one man.

**Comment by cmgmyr** [comment]
Cool, I'll get that implemented today

**Comment by askaoru** [comment]
Perfect. That could be used in a lot of places. Thanks @cmgmyr ! :+1:

**Comment by a-komarev** [comment]
@cmgmyr thanks! Very useful function.

**Comment by cmgmyr** [comment]
This is now in the latest `2.6` release.
