### ISSUE TITLE
Getting latest results

### ISSUE THREAD

**Issue by lstables** [cmgmyr/laravel-messenger#63]
Using the following method form the example:

````
public function show($id)
    {
        try {
            $thread = Thread::findOrFail($id);
        } catch (ModelNotFoundException $e) {
            Session::flash('error_message', 'The thread with ID: ' . $id . ' was not found.');

            return redirect('account/messages');
        }

        // don't show the current user in list
        $userId = Auth::id();
        $users = User::whereNotIn('id', $thread->participantsUserIds($userId))->get();

        return view('messages.show', compact('thread', 'users'));
    }
````

I can't get the messages to show in latest order:

![](http://cl.ly/image/41310p1S2b3p/download/Screen%20Shot%202015-08-13%20at%2019.26.02.png) Need the latest time to show first rather than last. How can I achieve this?

**Comment by cmgmyr** [comment]
No problem, in your view you can replace [this](https://github.com/cmgmyr/laravel-messenger/blob/master/src/Cmgmyr/Messenger/examples/views/messenger/show.blade.php#L7) with...

```php
@foreach($thread->messages()->latest()->get() as $message)
```

Since the thread's messages is just a raw relationship, you can do anything that you want with it. If you didn't want this in the view, you could always do this in the controller and just pass through the messages.

I hope that helps. Just let me know if you have any more questions.

**Comment by lstables** [comment]
Awesome thanks Chris I knew there'd be a work around easy way, just couldn't figure it out!! Thanks again man.

**Comment by cmgmyr** [comment]
:+1:
